### ISSUE TITLE
clarification for files/locations needed

### ISSUE THREAD

**Issue by ghost** [mkomon/uota#1]
am I correct that my project folder will need to contain:
-  a copy of your uota.py module from this lib section
- an adjusted version of your uota.cfg.example as uota.cfg
- a copy of my micropython .bin file
- all my .py files used in my project
and I will create a .gz file with all the contents of this folder into a new folder (e.g. .../esp32upload?
In addition add the adjusted text file "latest" into this folder

then uota.cfg url could be "http://localhost/.../esp32upload/"

and where is the module connect_wifi coming from and how do I provide credentials for the connection?

**Comment by mkomon** [comment]
uOTA updates code written in MicroPython stored in flash; it cannot update MicroPython itself that is flashed in the MCU. It's not possible to update MicroPython from MicroPython at all as far as I am aware.

Instead of a copy of micropython .bin file you need to create a .tar.gz archive of the new version of your MicroPython code and publish it on a HTTP(S) server together with `latest` file that refers to the filename of the .tar.gz archive.

The files `uota.py`, `uota.cfg` and `version` go to the MCU flash; `some_new_firmware.tar.gz` and `latest` go to the HTTP(S) server.

`uota.cfg` URL must refer to the server where new firmware can be found. `Localhost` would refer to the MCU running MicroPython itself which would not work. The IP address of the HTTP(S) server or DNS name must be used in the URL. You probably want to use an IP address if you are updating within a LAN without a local DNS server with local DNS records and you probably want to use a DNS name if your server is in the Internet.

It is assumed that you provide network connection yourself and handle storing/providing wifi credentials as is appropriate for your project. Below is what I use for connect_wifi.py in all of my projects.

```python
# connect_wifi.py
#
# version 0.1

import network
import utime


def connect_wifi(ssid = '', password = ''):
    """
    Connect to wifi and return wifi radio object.
    
    """
    wifi = network.WLAN(network.STA_IF)
    wifi.active(True)
    wifi.connect(ssid, password)
    while not wifi.isconnected():
        utime.sleep(1)
        print('WiFi connect retry ...')
    print('WiFi IP:', wifi.ifconfig()[0])
    print('WiFi cfg:', wifi.ifconfig())
    return wifi
```

**Comment by ghost** [comment]
Hi Martin
Thanks for these clarifications and for sharing your project.
As I understand I will have to load "connect_wifi.py" also into the MCU as it will be needed for my code updates to work.
Was a bit confused that you name the self written py-scripts firmware as for me the firmware would relate to the uPython-bin file and my scripts would be the app that gets run - but that's just a side note.

**Comment by mkomon** [comment]
Providing a working network/Internet connection is out of the scope of uOTA and network connection is expected before uOTA is used to check for updates. I use the `connect_wifi.py` as provided above and call it from my `boot.py` to establish network connection at startup since my projects tend to require Internet connection to work anyway.

I am aware of the confusion about the word "firmware" and I understand where you are coming from. I wrote uOTA with a product in mind where I see the MicroPython application code as a part of device firmware. I'll clarify this further if this causes confusion with more people.

**Comment by ph-wheels** [comment]
I really like this method of doing ota update, nice library, thanks.

Initially it was not clear that the `version` file should be part of `firmware.tar.g` file holding the updated version number as to prevent it from updating each time, I however found an alternative way which avoid having to update or keep track.
Place a `version` file once in your esp32 directory and then add following uota update code piece in your `main.py` file

`            if do_ota_update and uota.check_for_updates():
                uota.install_new_firmware()
                with open('version', 'w') as myfile:
                    myfile.write(''.join(ver).join('\r\n'))
                    myfile.close()
                machine.reset()`

Obviously there should be a variable within your `main.py` which hold the version of your program like:

`ver = '2.0.1'`

**Comment by mkomon** [comment]
Closing as old and non-actionable. Please open a new issue if there are any things for me to look at, thank you.

**Comment by ph-wheels** [comment]
Ok
